#!/usr/bin/env python3
import json
import os
import sys
import subprocess

if len(sys.argv) < 3:
    print("Usage: notify-user <title> <message>")
    sys.exit(1)

title = sys.argv[1]
message = sys.argv[2]

# print(json.dumps(json.loads(os.environ.__str__()), indent=4))
subprocess.run(["notify-send", title, message])